version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bjj_postgres
    environment:
      POSTGRES_USER: bjj_user
      POSTGRES_PASSWORD: bjj_pass123
      POSTGRES_DB: bjj_academy_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bjj_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bjj_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bjj_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bjjacademy.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
